### ISSUE TITLE
Runtime error in browser-example

### ISSUE THREAD

**Issue by Paleocene** [Kotlin/kotlin-wasm-examples#20]
I'm trying to run the `browser-example` out of the box, however it fails with a runtime error (see also screenshot): `wasm validation error: at offset 22982: incompatible super type`.

This is using Firefox nightly 117.0a1, with the required flags both enabled.

![image](https://github.com/Kotlin/kotlin-wasm-examples/assets/123772937/1424cbe4-1a68-4082-8476-daca72ed389a)

**Comment by bashor** [comment]
Thanks, it's a known issue https://bugzilla.mozilla.org/show_bug.cgi?id=1843392.
Folks from Mozilla are going to make a fix on their side.
