### ISSUE TITLE
Doesn't run on Firefox Nightly

### ISSUE THREAD

**Issue by GuilhE** [Kotlin/kotlin-wasm-examples#22]
Trying to run but it fails on Firefox 115.0.2 and Firefox Nightly 117.0a1 with this:

> GET http://localhost:8080/favicon.ico[HTTP/1.1 404 Not Found 0ms] 
> 
> Using experimental Kotlin/Wasm may require enabling experimental features in the target environment. - Chrome: enable WebAssembly Garbage Collection at chrome://flags/#enable-webassembly-garbage-collection or run the program with the --js-flags=--experimental-wasm-gc command line argument. - Firefox: enable javascript.options.wasm_function_references and javascript.options.wasm_gc at about:config. - Edge: run the program with the --js-flags=--experimental-wasm-gc command line argument. - Node.js: run the program with the --experimental-wasm-gc command line argument. For more information see https://kotl.in/wasm_help/.  jetsnackwasmapp.uninstantiated.mjs:4040:19
> 
> Uncaught CompileError: wasm validation error: at offset 525346: incompatible super type
>     instantiate http://localhost:8080/jetsnackwasmapp.uninstantiated.mjs:4020
>     async* http://localhost:8080/load.mjs:7
>  jetsnackwasmapp.wasm:4020

**Comment by bashor** [comment]
Thanks, it's a known issue https://bugzilla.mozilla.org/show_bug.cgi?id=1843392.
Folks from Mozilla are going to make a fix on their side.
