### ISSUE TITLE
kotlin-wasm-examples/browser-example build and run,Why is an error reported when importing wasm files: Unknown type kind: -49

### ISSUE THREAD

**Issue by pengxiaohua575527452** [Kotlin/kotlin-wasm-examples#26]
![image](https://github.com/Kotlin/kotlin-wasm-examples/assets/40903072/5eb7ccf2-1cfe-4148-8c58-d53abeca1e21)
I am using the http-server service。
Shouldn't we get the following results？
![image](https://github.com/Kotlin/kotlin-wasm-examples/assets/40903072/b9c65236-b6d5-4f24-955b-da1a79e70fb2)
What did I do wrong??

**Comment by bashor** [comment]
Which version of Kotlin is used there? 
Which browser and version do you use?

**Comment by bashor** [comment]
Anyway, it looks like a bug in the browser, please file an issue.
