### ISSUE TITLE
 CompileError: wasm validation error: at offset 410: bad type

### ISSUE THREAD

**Issue by vipwp** [Kotlin/kotlin-wasm-examples#3]
I clone the code and build in EAP ideal but get the error message in console.

os: windows 10
browser: Firefox 111.0 x64
 jdk: Eclipse adoptium 11
kotlin version:     kotlin("multiplatform") version "1.8.20-RC2"

![image](https://user-images.githubusercontent.com/1547414/228214379-fc2672ed-1ae0-41be-b961-ff12f5a1f3f5.png)

**Comment by zezulaon** [comment]
I got the same error in Firefox. Chrome 112 (arm64) seems to be working though

**Comment by bashor** [comment]
Technically it could work with Firefox 112 (even 111 in simple casses), but the required options are available only in the Nightly builds now, but may change in the future (cc @eqrion).

**Comment by bashor** [comment]
Please let us know here if it doesn't work in Firefox Nightly 112+

**Comment by zezulaon** [comment]
Just tried Nightly build and it works - thanks for the info.
